palette = "catppuccin_macchiato"

### Replaced with [character]
# [](bg:lavender)\
# $os\
# $username\
# [](bg:surface1 fg:lavender)\

format = """
[$character](bg:surface1)\
$directory\
[](fg:surface1 bg:surface2)\
$git_branch\
$git_status\
[](fg:surface2 bg:overlay0)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:overlay0 bg:overlay1)\
$docker_context\
[](fg:overlay1 bg:Subtext1)\
$time\
[ ](fg:Subtext1)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:lavender darktext"
style_root = "bg:lavender darktext"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:lavender darktext"
disabled = true # Disabled by default

[os.symbols]
Ubuntu = ""

[character]
success_symbol = "[](fg:lavender)[󰄛 ](bg:lavender bold darktext)[](bg:surface1 fg:lavender)"
error_symbol = "[](fg:red)[󰙗 ](bg:red bold darktext)[](bg:surface1 fg:red)"

[directory]
style = "bg:surface1 yellow"
format = "[$path ]($style)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
home_symbol = "~"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" =trunc " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:overlay1 maroon"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:surface2 peach"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:surface2 peach"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:overlay0 sapphire"
version_format = '${raw}'
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:Subtext1 darktext"
format = '[   $time ]($style)'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
darktext= "#4c4f69"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"